# Generated by Django 5.2.17 on 2026-08-21 14:31

import django.db.models.deletion
from django.db import migrations, models

from core.rls import organization_scoped_policy_sql

CREATE_SCHEMA = "create schema if not exists integrations;"
DROP_SCHEMA = ""  # left in place - dropping would cascade any data in it

ENABLE_RLS = organization_scoped_policy_sql("integrations", "shopify_connections")
DISABLE_RLS = """
    drop policy if exists shopify_connections_tenant_isolation on "integrations"."shopify_connections";
    alter table "integrations"."shopify_connections" disable row level security;
"""


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(sql=CREATE_SCHEMA, reverse_sql=DROP_SCHEMA),
        migrations.CreateModel(
            name='ShopifyConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop_domain', models.CharField(max_length=255, unique=True)),
                ('access_token', models.CharField(max_length=255)),
                ('webhook_secret', models.CharField(max_length=255)),
                ('currency', models.CharField(blank=True, default='', max_length=10)),
                ('is_connected', models.BooleanField(default=False)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.organization')),
            ],
            options={
                'db_table': '"integrations"."shopify_connections"',
                'constraints': [models.UniqueConstraint(fields=('organization',), name='integrations_one_shopify_connection_per_org')],
            },
        ),
        migrations.RunSQL(sql=ENABLE_RLS, reverse_sql=DISABLE_RLS),
    ]
