# Generated by Django 5.2.17 on 2026-08-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifyconnection',
            name='auto_sync_orders',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shopifyconnection',
            name='shop_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='shopifyconnection',
            name='webhooks_active',
            field=models.BooleanField(default=False),
        ),
    ]
