# Generated by Django 5.2.17 on 2026-08-24 14:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('integrations', '0002_shopifyconnection_auto_sync_orders_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopifySyncJob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('mode', models.CharField(choices=[('full', 'Full'), ('incremental', 'Incremental'), ('custom', 'Custom Range')], max_length=15)),
                ('range_from', models.DateTimeField(blank=True, null=True)),
                ('range_to', models.DateTimeField(blank=True, null=True)),
                ('pages_fetched', models.PositiveIntegerField(default=0)),
                ('total_fetched', models.PositiveIntegerField(default=0)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.CharField(blank=True, default='', max_length=500)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.organization')),
            ],
            options={
                'db_table': '"integrations"."shopify_sync_jobs"',
                'ordering': ['-created_at'],
            },
        ),
    ]
