# Generated by Django 5.2.17 on 2026-08-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_shopifysyncjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopifysyncjob',
            name='range_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shopifysyncjob',
            name='range_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
