# Generated by Django 5.2.17 on 2026-08-24 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0005_shopifysyncjob_cancel_requested_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifysyncjob',
            name='skipped_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
