# Generated by Django 5.2.17 on 2026-08-25 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0006_shopifysyncjob_skipped_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifyconnection',
            name='webhook_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='shopifysyncjob',
            name='resume_cursor',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopifysyncjob',
            name='total_available',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
