# Generated by Django 5.2.17 on 2026-08-25 14:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('integrations', '0007_shopifyconnection_webhook_ids_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartlaneConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('api_key', models.CharField(blank=True, default='', max_length=255)),
                ('webhook_secret', models.CharField(max_length=255)),
                ('webhook_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_connected', models.BooleanField(default=False)),
                ('webhooks_active', models.BooleanField(default=False)),
                ('last_event_at', models.DateTimeField(blank=True, null=True)),
                ('events_received_count', models.PositiveIntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.organization')),
            ],
            options={
                'db_table': '"integrations"."smartlane_connections"',
                'constraints': [models.UniqueConstraint(fields=('organization',), name='integrations_one_smartlane_connection_per_org')],
            },
        ),
    ]
