# Generated by Django 5.2.17 on 2026-08-26 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0008_smartlaneconnection'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifysyncjob',
            name='ranges',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='shopifysyncjob',
            name='mode',
            field=models.CharField(choices=[('full', 'Full'), ('incremental', 'Incremental'), ('custom', 'Custom Range'), ('backfill', 'Gap Backfill')], max_length=15),
        ),
    ]
