# Generated by Django 5.2.17 on 2026-08-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0009_shopifysyncjob_ranges_alter_shopifysyncjob_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartlaneconnection',
            name='store_warehouse_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
