# Generated by Django 5.2.17 on 2026-09-07 10:17

import django.db.models.deletion
import uuid
from django.db import migrations, models

from core.rls import organization_scoped_policy_sql

# Only smartlane_store_links carries an organization_id - the config and
# courier catalog are platform-level and deliberately have no tenant column
# to scope by. Defense-in-depth for direct Postgres/PostgREST access only;
# Django's own isolation is TenantScopedModel's manager (see core/rls.py).
ENABLE_RLS = organization_scoped_policy_sql("integrations", "smartlane_store_links")
DISABLE_RLS = """
    drop policy if exists smartlane_store_links_tenant_isolation on "integrations"."smartlane_store_links";
    alter table "integrations"."smartlane_store_links" disable row level security;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_membership_allowed_modules_audits'),
        ('integrations', '0010_smartlaneconnection_store_warehouse_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartlaneBusinessConfig',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('business_code', models.CharField(blank=True, default='', max_length=100)),
                ('client_id', models.CharField(blank=True, default='', max_length=255)),
                ('client_secret', models.CharField(blank=True, default='', max_length=255)),
                ('jwt_token', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=False)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_verify_error', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': '"integrations"."smartlane_business_config"',
            },
        ),
        migrations.CreateModel(
            name='SmartlaneCourierOffering',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('key', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=100)),
                ('carrier_name', models.CharField(blank=True, default='', max_length=100)),
                ('service_type', models.CharField(choices=[('overnight', 'Overnight'), ('overland', 'Overland')], default='overland', max_length=20)),
                ('warehouse_name_template', models.CharField(blank=True, default='{org} - {carrier}', max_length=150)),
                ('auto_booking', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, default='', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': '"integrations"."smartlane_courier_offerings"',
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='SmartlaneStoreLink',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending approval'), ('rejected', 'Rejected'), ('in_review', 'In review with Smartlane'), ('active', 'Active'), ('in_active', 'Inactive')], default='draft', max_length=20)),
                ('kyc_name', models.CharField(blank=True, default='', max_length=255)),
                ('kyc_logo_url', models.URLField(blank=True, default='', max_length=500)),
                ('kyc_platform', models.CharField(blank=True, default='api', max_length=50)),
                ('kyc_industry', models.CharField(blank=True, default='', max_length=150)),
                ('kyc_ntn', models.CharField(blank=True, default='', max_length=50)),
                ('kyc_years_in_business', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('kyc_business_address', models.CharField(blank=True, default='', max_length=500)),
                ('kyc_avg_order_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('kyc_avg_monthly_sales', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('kyc_annual_retail_sales', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('kyc_poc_name', models.CharField(blank=True, default='', max_length=150)),
                ('kyc_email', models.CharField(blank=True, default='', max_length=255)),
                ('kyc_phone', models.CharField(blank=True, default='', max_length=50)),
                ('requested_offerings', models.JSONField(blank=True, default=list)),
                ('smartlane_store_id', models.CharField(blank=True, default='', max_length=100)),
                ('requested_by_user_id', models.UUIDField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by_email', models.CharField(blank=True, default='', max_length=255)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.CharField(blank=True, default='', max_length=500)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_submit_response', models.JSONField(blank=True, default=dict)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.organization')),
            ],
            options={
                'db_table': '"integrations"."smartlane_store_links"',
                'constraints': [models.UniqueConstraint(fields=('organization',), name='integrations_one_smartlane_store_per_org')],
            },
        ),
        migrations.RunSQL(sql=ENABLE_RLS, reverse_sql=DISABLE_RLS),
    ]
