# Generated by Django 5.2.17 on 2026-09-07 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0010_smartlaneconnection_store_warehouse_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartlaneBusinessConfig',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('business_code', models.CharField(blank=True, default='', max_length=100)),
                ('client_id', models.CharField(blank=True, default='', max_length=255)),
                ('client_secret', models.CharField(blank=True, default='', max_length=255)),
                ('jwt_token', models.TextField(blank=True, default='')),
                ('registered_ip', models.CharField(blank=True, default='', max_length=64)),
                ('is_active', models.BooleanField(default=False)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_verify_error', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': '"integrations"."smartlane_business_config"',
            },
        ),
    ]
