# Generated by Django 5.2.17 on 2026-09-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0011_smartlanebusinessconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartlaneCourierOffering',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('key', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=100)),
                ('carrier_name', models.CharField(blank=True, default='', max_length=100)),
                ('service_type', models.CharField(choices=[('overnight', 'Overnight'), ('overland', 'Overland')], default='overland', max_length=20)),
                ('warehouse_name_template', models.CharField(blank=True, default='{org} - {carrier}', max_length=150)),
                ('auto_booking', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, default='', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': '"integrations"."smartlane_courier_offerings"',
                'ordering': ['sort_order', 'label'],
            },
        ),
    ]
