# Generated by Django 5.2.17 on 2026-09-08 07:03

import django.db.models.deletion
from django.db import migrations, models

from core.rls import organization_scoped_policy_sql

# smartlane_store_warehouses carries an organization_id (TenantScopedModel),
# so it gets the standard per-org policy - same convention as
# smartlane_store_links in 0011.
ENABLE_RLS = organization_scoped_policy_sql("integrations", "smartlane_store_warehouses")
DISABLE_RLS = """
    drop policy if exists smartlane_store_warehouses_tenant_isolation on "integrations"."smartlane_store_warehouses";
    alter table "integrations"."smartlane_store_warehouses" disable row level security;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_membership_allowed_modules_audits'),
        ('integrations', '0011_smartlanebusinessconfig_smartlanecourieroffering_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartlanestorelink',
            name='kyc_city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='smartlanestorelink',
            name='kyc_zip_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.CreateModel(
            name='SmartlaneStoreWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('smartlane_warehouse_code', models.CharField(blank=True, default='', max_length=100)),
                ('name', models.CharField(blank=True, default='', max_length=150)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('failed', 'Failed'), ('revoked', 'Revoked')], default='pending', max_length=20)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_provision_error', models.CharField(blank=True, default='', max_length=500)),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='integrations.smartlanecourieroffering')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.organization')),
                ('store_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='integrations.smartlanestorelink')),
            ],
            options={
                'db_table': '"integrations"."smartlane_store_warehouses"',
                'constraints': [models.UniqueConstraint(fields=('store_link', 'offering'), name='integrations_one_warehouse_per_store_offering')],
            },
        ),
        migrations.RunSQL(sql=ENABLE_RLS, reverse_sql=DISABLE_RLS),
    ]
