# Generated by Django 5.2.17 on 2026-09-23 10:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_membership_allowed_modules_audits'),
        ('integrations', '0015_shopifyconnection_push_status_to_shopify'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartlaneRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('webhook', 'Webhook'), ('warehouse_edit', 'Warehouse edit/revoke'), ('finance', 'Finance application')], max_length=20)),
                ('status', models.CharField(choices=[('pending_approval', 'Pending approval'), ('rejected', 'Rejected'), ('approved', 'Approved')], default='pending_approval', max_length=20)),
                ('payload', models.JSONField(default=dict)),
                ('requested_by_user_id', models.UUIDField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by_email', models.CharField(blank=True, default='', max_length=255)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.CharField(blank=True, default='', max_length=500)),
                ('last_response', models.JSONField(blank=True, default=dict)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.organization')),
                ('store_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='integrations.smartlanestorelink')),
            ],
            options={
                'db_table': '"integrations"."smartlane_requests"',
                'ordering': ['-requested_at', '-created_at'],
            },
        ),
    ]
