# Generated by Django 5.2.17 on 2026-09-29 09:25
# Hand-edited: added the barqraftar_integrations schema (own schema per the
# user's request, kept separate from Smartlane/Shopify's "integrations"
# schema) and RLS policies for all three tables, matching the pattern used
# by every other integrations migration - see 0001_initial.py (schema
# creation) and 0011_smartlanebusinessconfig_...py (multi-table RLS).

import django.db.models.deletion
import uuid
from django.db import migrations, models

from core.rls import organization_scoped_policy_sql

CREATE_SCHEMA = "create schema if not exists barqraftar_integrations;"
DROP_SCHEMA = ""  # left in place - dropping would cascade any data in it

ENABLE_RLS = (
    organization_scoped_policy_sql("barqraftar_integrations", "connections")
    + organization_scoped_policy_sql("barqraftar_integrations", "shipments")
    + organization_scoped_policy_sql("barqraftar_integrations", "sync_jobs")
)
DISABLE_RLS = """
    drop policy if exists connections_tenant_isolation on "barqraftar_integrations"."connections";
    alter table "barqraftar_integrations"."connections" disable row level security;

    drop policy if exists shipments_tenant_isolation on "barqraftar_integrations"."shipments";
    alter table "barqraftar_integrations"."shipments" disable row level security;

    drop policy if exists sync_jobs_tenant_isolation on "barqraftar_integrations"."sync_jobs";
    alter table "barqraftar_integrations"."sync_jobs" disable row level security;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_membership_allowed_modules_audits'),
        ('integrations', '0016_smartlanerequest'),
        ('oms', '0023_order_supabase_order_no'),
    ]

    operations = [
        migrations.RunSQL(sql=CREATE_SCHEMA, reverse_sql=DROP_SCHEMA),
        migrations.CreateModel(
            name='BarqRaftarSyncJob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('cancel_requested', models.BooleanField(default=False)),
                ('checked_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('total_available', models.PositiveIntegerField(blank=True, null=True)),
                ('error_message', models.CharField(blank=True, default='', max_length=500)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.organization')),
            ],
            options={
                'db_table': '"barqraftar_integrations"."sync_jobs"',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BarqRaftarConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('api_key', models.CharField(blank=True, default='', max_length=255)),
                ('api_secret', models.CharField(blank=True, default='', max_length=255)),
                ('is_connected', models.BooleanField(default=False)),
                ('webhook_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('last_event_at', models.DateTimeField(blank=True, null=True)),
                ('events_received_count', models.PositiveIntegerField(default=0)),
                ('pickup_address_id', models.CharField(blank=True, default='', max_length=100)),
                ('pickup_address_label', models.CharField(blank=True, default='', max_length=255)),
                ('from_city_id', models.CharField(blank=True, default='', max_length=50)),
                ('from_city_name', models.CharField(blank=True, default='', max_length=150)),
                ('create_pickup_request', models.BooleanField(default=True)),
                ('default_weight_grams', models.PositiveIntegerField(default=500)),
                ('label_format', models.CharField(default='a4', max_length=10)),
                ('cities_cache', models.JSONField(blank=True, default=list)),
                ('cities_cached_at', models.DateTimeField(blank=True, null=True)),
                ('city_aliases', models.JSONField(blank=True, default=dict)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.organization')),
            ],
            options={
                'db_table': '"barqraftar_integrations"."connections"',
                'constraints': [models.UniqueConstraint(fields=('organization',), name='barqraftar_one_connection_per_org')],
            },
        ),
        migrations.CreateModel(
            name='BarqRaftarShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_id', models.CharField(max_length=100)),
                ('tracking_number', models.CharField(blank=True, default='', max_length=100)),
                ('status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('status_label', models.CharField(blank=True, default='', max_length=100)),
                ('status_logs', models.JSONField(blank=True, default=list)),
                ('last_payload', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('pickup_requested', models.BooleanField(default=False)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barqraftar_shipments', to='oms.order')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.organization')),
            ],
            options={
                'db_table': '"barqraftar_integrations"."shipments"',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'is_active', 'last_checked_at'], name='barqraftar_shipment_poll_idx'), models.Index(fields=['organization', 'tracking_number'], name='barqraftar_shipment_tn_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'reference_id'), name='barqraftar_reference_unique_per_org'), models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('order',), name='barqraftar_one_active_shipment_per_order')],
            },
        ),
        migrations.RunSQL(sql=ENABLE_RLS, reverse_sql=DISABLE_RLS),
    ]
