# Generated by Django 5.2.17 on 2026-09-30 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_membership_allowed_modules_audits'),
        ('integrations', '0017_barqraftar'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='smartlaneconnection',
            name='integrations_one_smartlane_connection_per_org',
        ),
        migrations.AddField(
            model_name='smartlaneconnection',
            name='kind',
            field=models.CharField(choices=[('own', "Organization's own account"), ('oms', 'OMS Courier')], default='own', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='smartlaneconnection',
            constraint=models.UniqueConstraint(fields=('organization', 'kind'), name='integrations_one_smartlane_connection_per_kind'),
        ),
    ]
