# Generated by Django 5.2.17 on 2026-10-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0018_smartlaneconnection_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='barqraftarconnection',
            name='account_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
