# Generated by Django 5.2.17 on 2026-10-10 16:16

import django.db.models.deletion
import uuid
from django.db import migrations, models

from core.rls import organization_scoped_policy_sql

# Carries an organization_id (TenantScopedModel), so it gets the standard
# per-org policy - same convention as smartlane_store_warehouses in 0012.
ENABLE_RLS = organization_scoped_policy_sql("integrations", "oms_courier_enrollments")
DISABLE_RLS = """
    drop policy if exists oms_courier_enrollments_tenant_isolation on "integrations"."oms_courier_enrollments";
    alter table "integrations"."oms_courier_enrollments" disable row level security;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_organization_is_platform'),
        ('integrations', '0021_postex_webhook'),
    ]

    operations = [
        migrations.CreateModel(
            name='OmsCourierEnrollment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('courier', models.CharField(choices=[('smartlane', 'Smartlane'), ('postex', 'PostEx'), ('barq_raftar', 'BarqRaftar')], max_length=20)),
                ('is_enabled', models.BooleanField(default=True)),
                ('store_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('pickup_address', models.CharField(max_length=500)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.organization')),
            ],
            options={
                'db_table': '"integrations"."oms_courier_enrollments"',
                'constraints': [models.UniqueConstraint(fields=('organization', 'courier'), name='integrations_one_oms_courier_enrollment')],
            },
        ),
        migrations.RunSQL(sql=ENABLE_RLS, reverse_sql=DISABLE_RLS),
    ]
