export const API_ENDPOINTS = {
  health: "/api/core/health/",
  healthProtected: "/api/core/health/protected/",
  admin: {
    organizations: "/api/core/admin/organizations/",
    organization: (id) => `/api/core/admin/organizations/${id}/`,
    user: (id) => `/api/core/admin/users/${id}/`,
  },
  team: "/api/core/team/",
  teamMember: (userId) => `/api/core/team/${userId}/`,
  auditLogs: "/api/core/audit-logs/",
  oms: {
    orders: "/api/oms/orders/",
    orderCounts: "/api/oms/orders/counts/",
    orderDashboard: "/api/oms/orders/dashboard/",
    orderReturnsSummary: "/api/oms/orders/returns-summary/",
    orderBulkAction: "/api/oms/orders/bulk-action/",
    orderScanDispatch: "/api/oms/orders/scan-dispatch/",
    orderScanReturn: "/api/oms/orders/scan-return/",
    orderExport: "/api/oms/orders/export/",
    orderImport: "/api/oms/orders/import-csv/",
    orderSmartlaneAirwayBill: "/api/oms/orders/smartlane-airway-bill/",
    orderSmartlaneLoadSheet: "/api/oms/orders/smartlane-load-sheet/",
    couriers: "/api/oms/couriers/",
    report: "/api/oms/report/",
    printBatches: "/api/oms/print-batches/",
    printBatchDownload: (id) => `/api/oms/print-batches/${id}/download/`,
    order: (id) => `/api/oms/orders/${id}/`,
    orderNotes: (id) => `/api/oms/orders/${id}/notes/`,
    orderTransactions: (id) => `/api/oms/orders/${id}/transactions/`,
    orderLog: (id) => `/api/oms/orders/${id}/log/`,
    orderCustomerHistory: (id) => `/api/oms/orders/${id}/customer-history/`,
    orderSplitOrders: (id) => `/api/oms/orders/${id}/split-orders/`,
    orderSplit: (id) => `/api/oms/orders/${id}/split/`,
    orderLoadsheet: (id) => `/api/oms/orders/${id}/loadsheet/`,
    orderAirwayBill: (id) => `/api/oms/orders/${id}/airway-bill/`,
  },
  wms: {
    warehouses: "/api/wms/warehouses/",
    stock: "/api/wms/stock/",
    stockSummary: "/api/wms/stock/summary/",
    stockAdjust: (id) => `/api/wms/stock/${id}/adjust/`,
    stockImportSkus: "/api/wms/stock/import-skus/",
    movements: "/api/wms/movements/",
    returnScan: "/api/wms/returns/scan/",
  },
  // Added as modules land: finance
};

export default API_ENDPOINTS;
