# Generated by Django 5.2.17 on 2026-08-26 10:23

import django.db.models.deletion
import uuid
from django.db import migrations, models

from core.rls import organization_scoped_policy_sql

# Same defense-in-depth applied to oms tables (see oms/migrations/
# 0001_initial.py): protects direct Postgres/PostgREST access. Django's
# own isolation comes from TenantScopedModel + TenantMiddleware.
ENABLE_WMS_RLS = (
    organization_scoped_policy_sql("wms", "warehouses")
    + organization_scoped_policy_sql("wms", "stock_items")
    + organization_scoped_policy_sql("wms", "stock_movements")
)

DISABLE_WMS_RLS = """
    alter table "wms"."warehouses" disable row level security;
    alter table "wms"."stock_items" disable row level security;
    alter table "wms"."stock_movements" disable row level security;
"""


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=100)),
                ('product_name', models.CharField(blank=True, default='', max_length=255)),
                ('quantity', models.IntegerField(default=0)),
                ('reorder_level', models.PositiveIntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.organization')),
            ],
            options={
                'db_table': '"wms"."stock_items"',
                'ordering': ['sku'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('delta', models.IntegerField()),
                ('balance_after', models.IntegerField()),
                ('reason', models.CharField(choices=[('order_dispatch', 'Order Dispatch'), ('return_restock', 'Return Restock'), ('manual_adjustment', 'Manual Adjustment'), ('initial', 'Initial Stock')], max_length=20)),
                ('order_number', models.CharField(blank=True, default='', max_length=50)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('actor_user_id', models.UUIDField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.organization')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='wms.stockitem')),
            ],
            options={
                'db_table': '"wms"."stock_movements"',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.organization')),
            ],
            options={
                'db_table': '"wms"."warehouses"',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='stockitem',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='wms.warehouse'),
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='wms_warehouse_code_per_org'),
        ),
        migrations.AddConstraint(
            model_name='stockitem',
            constraint=models.UniqueConstraint(fields=('organization', 'warehouse', 'sku'), name='wms_stock_sku_per_warehouse'),
        ),
        migrations.RunSQL(sql=ENABLE_WMS_RLS, reverse_sql=DISABLE_WMS_RLS),
    ]
