# Generated by Django 5.2.17 on 2026-09-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='reason',
            field=models.CharField(choices=[('order_dispatch', 'Order Dispatch'), ('return_restock', 'Return Restock'), ('manual_adjustment', 'Manual Adjustment'), ('initial', 'Initial Stock'), ('shopify_sync', 'Shopify Inventory Sync')], max_length=20),
        ),
    ]
