# Generated by Django 5.2.17 on 2026-09-01 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_membership_allowed_modules_audits'),
        ('wms', '0002_alter_stockmovement_reason'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stockitem',
            name='wms_stock_sku_per_warehouse',
        ),
        migrations.AddField(
            model_name='stockitem',
            name='shopify_inventory_item_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='sku',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='stockitem',
            constraint=models.UniqueConstraint(condition=models.Q(('shopify_inventory_item_id__isnull', True)), fields=('organization', 'warehouse', 'sku'), name='wms_stock_sku_per_warehouse'),
        ),
        migrations.AddConstraint(
            model_name='stockitem',
            constraint=models.UniqueConstraint(condition=models.Q(('shopify_inventory_item_id__isnull', False)), fields=('organization', 'warehouse', 'shopify_inventory_item_id'), name='wms_stock_shopify_item_per_warehouse'),
        ),
    ]
