# Generated by Django 5.2.17 on 2026-08-21 13:22

import django.db.models.deletion
import uuid
from django.db import migrations, models

from core.rls import organization_scoped_policy_sql

ENABLE_OMS_RLS = organization_scoped_policy_sql("oms", "orders") + organization_scoped_policy_sql(
    "oms", "order_items"
)

DISABLE_OMS_RLS = """
    drop policy if exists orders_tenant_isolation on "oms"."orders";
    alter table "oms"."orders" disable row level security;
    drop policy if exists order_items_tenant_isolation on "oms"."order_items";
    alter table "oms"."order_items" disable row level security;
"""


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(max_length=50)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_phone', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('fulfilled', 'Fulfilled')], default='pending', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.organization')),
            ],
            options={
                'db_table': '"oms"."orders"',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='oms.order')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.organization')),
            ],
            options={
                'db_table': '"oms"."order_items"',
            },
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('organization', 'order_number'), name='oms_order_number_per_org'),
        ),
        migrations.RunSQL(sql=ENABLE_OMS_RLS, reverse_sql=DISABLE_OMS_RLS),
    ]
