# Generated by Django 5.2.17 on 2026-08-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('oms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shopify_order_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('shopify_order_id__isnull', False)), fields=('organization', 'shopify_order_id'), name='oms_shopify_order_id_per_org'),
        ),
    ]
