# Generated by Django 5.2.17 on 2026-08-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oms', '0005_order_address_line1_order_address_line2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='weight_grams',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
