# Generated by Django 5.2.17 on 2026-08-24 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oms', '0006_orderitem_weight_grams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='postal_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
