# Generated by Django 5.2.17 on 2026-08-26 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oms', '0009_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('pending_cc', 'Pending CC'), ('pending_cod', 'Pending COD'), ('city_issue', 'City Issue'), ('awaiting_assigning', 'Awaiting Assigning'), ('awaiting_approval', 'Awaiting Approval'), ('approved', 'Approved'), ('ready_to_print', 'Ready to Print'), ('ready_to_pick', 'Ready to Pick'), ('dispatch_issue', 'Dispatch Issue'), ('awaiting_dispatched', 'Awaiting Dispatched'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], default='pending_cod', max_length=30),
        ),
    ]
