# Generated by Django 5.2.17 on 2026-08-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oms', '0011_order_return_received_at_order_return_received_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='tag',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
