# Generated by Django 5.2.17 on 2026-09-01 08:58

import django.db.models.deletion
import oms.models
import uuid
from django.db import migrations, models

from core.rls import organization_scoped_policy_sql

ENABLE_PRINT_BATCH_RLS = organization_scoped_policy_sql("oms", "print_batches")
DISABLE_PRINT_BATCH_RLS = 'alter table "oms"."print_batches" disable row level security;'


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_membership_allowed_modules_audits'),
        ('oms', '0012_order_invoice_number_order_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('pending_cc', 'Pending CC'), ('pending_cod', 'Pending COD'), ('city_issue', 'City Issue'), ('awaiting_assigning', 'Awaiting Assigning'), ('awaiting_approval', 'Awaiting Approval'), ('approved', 'Approved'), ('booking_pending', 'Booking Pending'), ('ready_to_print', 'Ready to Print'), ('ready_to_pick', 'Ready to Pick'), ('dispatch_issue', 'Dispatch Issue'), ('awaiting_dispatched', 'Awaiting Dispatched'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], default='pending_cod', max_length=30),
        ),
        migrations.CreateModel(
            name='PrintBatch',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('loadsheet', 'Load Sheet'), ('airway_bill', 'Airway Bill')], max_length=15)),
                ('courier', models.CharField(blank=True, default='', max_length=50)),
                ('order_count', models.PositiveIntegerField(default=0)),
                ('order_numbers', models.JSONField(blank=True, default=list)),
                ('file', models.FileField(upload_to=oms.models._print_batch_upload_path)),
                ('content_type', models.CharField(default='application/pdf', max_length=100)),
                ('created_by_user_id', models.UUIDField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.organization')),
            ],
            options={
                'db_table': '"oms"."print_batches"',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunSQL(sql=ENABLE_PRINT_BATCH_RLS, reverse_sql=DISABLE_PRINT_BATCH_RLS),
    ]
