# Generated by Django 5.2.17 on 2026-09-01 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_membership_allowed_modules_audits'),
        ('oms', '0013_alter_order_status_printbatch'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['organization', 'status'], name='oms_order_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['organization', '-created_at'], name='oms_order_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['organization', '-placed_at'], name='oms_order_org_placed_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['organization', 'customer_phone'], name='oms_order_org_phone_idx'),
        ),
    ]
