# Generated by Django 5.2.17 on 2026-09-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oms', '0014_order_oms_order_org_status_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='packed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='packed_by_email',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='return_received_by_email',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
