# Generated by Django 5.2.17 on 2026-09-02 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oms', '0015_order_packed_at_order_packed_by_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='return_condition',
            field=models.CharField(blank=True, choices=[('good', 'Good'), ('bad', 'Bad')], default='', max_length=10),
        ),
    ]
