# Generated by Django 5.2.17 on 2026-09-14 09:31

import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.db import migrations, models

from core.rls import organization_scoped_policy_sql

ENABLE_TICKET_RLS = organization_scoped_policy_sql("oms", "tickets")
DISABLE_TICKET_RLS = 'alter table "oms"."tickets" disable row level security;'
ENABLE_TICKET_MESSAGE_RLS = organization_scoped_policy_sql("oms", "ticket_messages")
DISABLE_TICKET_MESSAGE_RLS = 'alter table "oms"."ticket_messages" disable row level security;'

# Backs Ticket.number - a short, human-facing sequential id ("TKT-000123")
# distinct from the UUID primary key. Created before the table so the
# column's db_default (nextval(...)) has something to reference; owned by
# the column afterwards so dropping the table drops the sequence with it.
CREATE_TICKET_NUMBER_SEQ = "create sequence if not exists oms.tickets_number_seq;"
DROP_TICKET_NUMBER_SEQ = "drop sequence if exists oms.tickets_number_seq;"
OWN_TICKET_NUMBER_SEQ = "alter sequence oms.tickets_number_seq owned by oms.tickets.number;"


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_membership_allowed_modules_audits'),
        ('oms', '0016_order_return_condition'),
    ]

    operations = [
        migrations.RunSQL(sql=CREATE_TICKET_NUMBER_SEQ, reverse_sql=migrations.RunSQL.noop),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.BigIntegerField(db_default=django.db.models.expressions.RawSQL("nextval('oms.tickets_number_seq')", []), editable=False, unique=True)),
                ('category', models.CharField(max_length=100)),
                ('sub_category', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('seen', 'Seen'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('created_by_user_id', models.UUIDField(blank=True, null=True)),
                ('created_by_email', models.CharField(blank=True, default='', max_length=255)),
                ('assigned_to_user_id', models.UUIDField(blank=True, null=True)),
                ('assigned_to_email', models.CharField(blank=True, default='', max_length=255)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by_user_id', models.UUIDField(blank=True, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='oms.order')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.organization')),
            ],
            options={
                'db_table': '"oms"."tickets"',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('author_user_id', models.UUIDField(blank=True, null=True)),
                ('author_role', models.CharField(choices=[('tenant', 'Tenant'), ('super_admin', 'Super Admin')], max_length=20)),
                ('author_email', models.CharField(blank=True, default='', max_length=255)),
                ('is_internal', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.organization')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='oms.ticket')),
            ],
            options={
                'db_table': '"oms"."ticket_messages"',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['organization', '-created_at'], name='oms_ticket_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['organization', 'created_by_user_id'], name='oms_ticket_org_author_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['organization', 'status'], name='oms_ticket_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['organization', 'priority'], name='oms_ticket_org_priority_idx'),
        ),
        migrations.RunSQL(sql=OWN_TICKET_NUMBER_SEQ, reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(sql=ENABLE_TICKET_RLS, reverse_sql=DISABLE_TICKET_RLS),
        migrations.RunSQL(sql=ENABLE_TICKET_MESSAGE_RLS, reverse_sql=DISABLE_TICKET_MESSAGE_RLS),
        # Reversing (unapplying) this migration drops the table via
        # CreateModel's own reverse first, then this drops the sequence -
        # correct order since nothing references it anymore by this point.
        migrations.RunSQL(sql=migrations.RunSQL.noop, reverse_sql=DROP_TICKET_NUMBER_SEQ),
    ]
