# Generated by Django 5.2.17 on 2026-10-10 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oms', '0024_order_dispatch_requested_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='platform_reference',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
    ]
