# Generated by Django 5.2.17 on 2026-08-21 13:22

import django.db.models.deletion
import uuid
from django.db import migrations, models

from core.rls import organization_scoped_policy_sql

# Schemas must exist before any CreateModel with a schema-qualified
# db_table can run. Helper functions (jwt_claim/is_super_admin/
# current_organization_id) live once in the core schema and are reused by
# every app's RLS policies (see core/rls.py).
CREATE_SCHEMAS_AND_HELPERS = """
    create extension if not exists "pgcrypto";

    create schema if not exists core;
    create schema if not exists oms;
    create schema if not exists wms;
    create schema if not exists finance;

    create or replace function core.jwt_claim(claim text)
    returns text
    language sql stable
    as $$
      select coalesce(
        auth.jwt() -> 'app_metadata' ->> claim,
        auth.jwt() -> 'user_metadata' ->> claim
      );
    $$;

    create or replace function core.is_super_admin()
    returns boolean
    language sql stable
    as $$
      select coalesce(core.jwt_claim('role'), '') = 'super_admin';
    $$;

    create or replace function core.current_organization_id()
    returns uuid
    language sql stable
    as $$
      select nullif(core.jwt_claim('organization_id'), '')::uuid;
    $$;
"""

DROP_HELPERS = """
    drop function if exists core.current_organization_id();
    drop function if exists core.is_super_admin();
    drop function if exists core.jwt_claim(text);
"""

# organizations has no organization_id column (it IS the tenant), so it
# gets a self-referential policy instead of the standard template.
ENABLE_CORE_RLS = (
    """
    alter table "core"."organizations" enable row level security;
    alter table "core"."organizations" force row level security;
    drop policy if exists organizations_tenant_isolation on "core"."organizations";
    create policy organizations_tenant_isolation on "core"."organizations"
      for all
      using (core.is_super_admin() or id = core.current_organization_id())
      with check (core.is_super_admin() or id = core.current_organization_id());
    """
    + organization_scoped_policy_sql("core", "memberships")
    + organization_scoped_policy_sql("core", "organization_modules")
)

DISABLE_CORE_RLS = """
    drop policy if exists organizations_tenant_isolation on "core"."organizations";
    alter table "core"."organizations" disable row level security;
    drop policy if exists memberships_tenant_isolation on "core"."memberships";
    alter table "core"."memberships" disable row level security;
    drop policy if exists organization_modules_tenant_isolation on "core"."organization_modules";
    alter table "core"."organization_modules" disable row level security;
"""


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(sql=CREATE_SCHEMAS_AND_HELPERS, reverse_sql=DROP_HELPERS),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('plan', models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('growth', 'Growth'), ('enterprise', 'Enterprise')], default='free', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': '"core"."organizations"',
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('role', models.CharField(choices=[('org_admin', 'Org Admin'), ('org_user', 'Org User')], default='org_user', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.organization')),
            ],
            options={
                'db_table': '"core"."memberships"',
                'constraints': [models.UniqueConstraint(fields=('organization', 'user_id'), name='core_membership_unique_user_per_org')],
            },
        ),
        migrations.CreateModel(
            name='OrganizationModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('oms', 'OMS'), ('wms', 'WMS'), ('finance', 'Finance')], max_length=20)),
                ('is_enabled', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='core.organization')),
            ],
            options={
                'db_table': '"core"."organization_modules"',
                'constraints': [models.UniqueConstraint(fields=('organization', 'module'), name='core_org_module_unique')],
            },
        ),
        migrations.RunSQL(sql=ENABLE_CORE_RLS, reverse_sql=DISABLE_CORE_RLS),
    ]
