# Generated by Django 5.2.17 on 2026-10-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_dispatchhubstore'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_platform',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.UniqueConstraint(condition=models.Q(('is_platform', True)), fields=('is_platform',), name='core_one_platform_organization'),
        ),
    ]
